---
# tasks file for toolbox

- name: Pull the latest ocp-toolbox
  git:
    repo: https://github.com/0xbboyd/ocp-toolbox.git
    dest: ~/src/utils/ocp-toolbox

- name: Build an ocp-toolbox container
  shell:
    chdir: ~/src/utils/ocp-toolbox
    cmd: buildah bud -f dockerfile -t ocp-toolbox:latest .

- name: Start and mount ocp-toolbox
  containers.podman.podman_container:
    name: ocp-toolbox
    image: ocp-toolbox:latest
    hostname: ocp-toolbox
    volume:
      - "{{ ocp-toolbox-host-src }}:/{{ ocp-toolbox-guest-src }}:O"
