---
# tasks file for toolbox

- name: Pull the latest ocp-toolbox
  git:
    repo: https://github.com/0xbboyd/ocp-toolbox.git
    dest: ~/src/utils/ocp-toolbox

- name: Build an ocp-toolbox container
  containers.podman.podman_image:
    name: ocp-toolbox
    path: "~/src/utils/ocp-toolbox"
    state: build
